### ISSUE TITLE
On reset cannot select previously selected option

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-contrib-mcq#186] opened 2022-10-20 12:05 UTC
### Subject of the issue
After resetting the question I cannot select an option if it was previously selected.

### Your environment
* v5.22.3, probably other versions
* observed in Firefox, Chrome, Edge, Safari (iOS), possibly others
* Windows, iOS, probably others

### Steps to reproduce
Allow multiple attempts at a question. Answer incorrectly and then hit reset. Note that you cannot select options that were previously selected.

### Expected behaviour
Any option should be selectable after reset.

**Comment by danielghost** [comment] 2023-01-04 17:55
This seems to be caused by the switch from `onClick` to `onChange` in https://github.com/adaptlearning/adapt-contrib-mcq/pull/176. The previous error is resolved by switching to `defaultChecked` only, and doesn't need the switch to `onChange`.

**Closed** 2023-03-13 10:37 UTC
Labels: bug
